/*
 * QUESTION BANK  -  Data Handling in R (course 3,230,1.00)
 * ---------------------------------------------------------
 * Each question is one object. Schema:
 *
 *   id          unique string, "<topicKey>-NNN"          (e.g. "prog-007")
 *   topic       one of the TOPIC keys defined in TOPICS below
 *   type        "tf" | "single" | "multi"
 *   prompt      the question text. Wrap inline code in backticks `like this`
 *   code        OPTIONAL multi-line code block shown in a monospace box
 *   options     array of strings. OMIT for "tf" (True/False is implied)
 *   answer      tf -> true/false | single -> option index | multi -> array of indices
 *   explanation short correction shown after answering
 *   source      where it comes from, for your own verification (hidden from stats)
 *   flagged     OPTIONAL true if unresolved / not confirmed in course materials -> verify this one first
 *
 * To add questions with Claude Code, just append objects to QUESTIONS.
 * Keep ids unique. Nothing else needs to change; the app reads TOPICS + QUESTIONS.
 *
 * NOTE ON THIS REVISION:
 * - All previously-flagged "bonus" items removed (course-first policy: 8 topics only, no extra section).
 * - Items testing functions/terms with no confirmed occurrence in course materials removed:
 *   tools-031, prog-030 (already bonus), import-024 (col_types), prep-018/019 (semi_join/anti_join),
 *   prep-026 (str_detect), apis-019 (pagination).
 * - Duplicate questions (same concept, reworded) trimmed to one instance each in nonrect, apis, viz.
 * - `source` lecture numbers corrected where evidence showed a different lecture teaches the material
 *   (nonrect HTML/rvest items -> Workshop 3; prep dplyr-verb/join items -> Lecture 8; viz aes/geom_point/
 *   facet_wrap/labs items -> Lecture 9).
 * - viz-012 rewritten to use geom_bar(stat = "identity"), the form actually taught, instead of geom_col().
 * - viz-010 (geom_boxplot) and nonrect-021 (html_elements) kept but flagged: not confirmed in extractable
 *   text, may be on an image slide -- check before relying on them.
 */

const TOPICS = [
  { key: "tools",   name: "Tools & Setup",            blurb: "R, RStudio, paths, help" },
  { key: "prog",    name: "Programming Basics",       blurb: "vectors, operators, loops, functions" },
  { key: "storage", name: "Data Storage & Encoding",  blurb: "binary, hex, floats, encoding" },
  { key: "import",  name: "Import & Rectangular Data", blurb: "readr, types, data frames, factors" },
  { key: "nonrect", name: "Non-Rectangular Data",      blurb: "XML, JSON, HTML, scraping" },
  { key: "apis",    name: "APIs",                      blurb: "httr2, requests, responses" },
  { key: "prep",    name: "Data Preparation",          blurb: "tidy, reshape, joins, dplyr" },
  { key: "viz",     name: "EDA & Visualisation",       blurb: "EDA, missing values, ggplot2" },
];

const QUESTIONS = [
  // ---------------- TOOLS & SETUP ----------------
  { id: "tools-001", topic: "tools", type: "tf",
    prompt: "In R, both `<-` and `=` can assign a value, but `<-` is the community convention.",
    answer: true,
    explanation: "Both work for assignment. `<-` is the preferred, conventional operator in R style guides.",
    source: "Lecture 1, assignment" },
  { id: "tools-002", topic: "tools", type: "single",
    prompt: "Which function returns your current working directory?",
    options: ["getwd()", "setwd()", "cwd()", "dir()"],
    answer: 0,
    explanation: "getwd() prints the working directory. setwd() changes it; dir() lists files.",
    source: "Lecture 1, working directory" },
  { id: "tools-003", topic: "tools", type: "single",
    prompt: "You want to run an entire saved script from the console. Which call does that?",
    code: "# script lives at code/clean.R",
    options: ["source(\"code/clean.R\")", "run(\"code/clean.R\")", "import(\"code/clean.R\")", "exec(\"code/clean.R\")"],
    answer: 0,
    explanation: "source() executes a whole R script file from disk in the current session.",
    source: "Lecture 1, source()" },
  { id: "tools-004", topic: "tools", type: "tf",
    prompt: "R vectors are indexed starting at 0.",
    answer: false,
    explanation: "R is 1-based. The first element is x[1], not x[0]. (This differs from Python.)",
    source: "Lecture 2, indexing" },
  { id: "tools-005", topic: "tools", type: "single",
    prompt: "What does `?sum` do?",
    options: ["Opens the help page for sum()", "Computes a running sum", "Checks if sum exists", "Prints the source code of sum()"],
    answer: 0,
    explanation: "A leading ? opens the documentation for a function.",
    source: "Lecture 1, help" },
  { id: "tools-006", topic: "tools", type: "single",
    prompt: "In a file path, what does `..` refer to?",
    options: ["The parent directory", "The current directory", "The home directory", "The root directory"],
    answer: 0,
    explanation: ".. is the parent folder; . is the current folder; ~ is home.",
    source: "Lecture 1, paths" },
  { id: "tools-007", topic: "tools", type: "tf",
    prompt: "In R, `#` begins a comment, and everything after it on that line is ignored when the code runs.",
    answer: true,
    explanation: "The hash starts a comment. R ignores the rest of the line, so it is used for notes to yourself.",
    source: "Lecture 1, comments" },
  { id: "tools-008", topic: "tools", type: "single",
    prompt: "Which call installs a package from CRAN?",
    options: ["`install.packages(\"dplyr\")`", "`library(dplyr)`", "`load(\"dplyr\")`", "`require.packages(\"dplyr\")`"],
    answer: 0,
    explanation: "install.packages() downloads and installs from CRAN. You only do this once per machine.",
    source: "Lecture 2, packages" },
  { id: "tools-009", topic: "tools", type: "single",
    prompt: "Which call loads an already-installed package so its functions are available this session?",
    options: ["`library(dplyr)`", "`install.packages(\"dplyr\")`", "`download(dplyr)`", "`use(dplyr)`"],
    answer: 0,
    explanation: "library() attaches an installed package. You call it every session you need the package.",
    source: "Lecture 2, packages" },
  { id: "tools-010", topic: "tools", type: "tf",
    prompt: "R object names are case sensitive, so `Data` and `data` refer to two different objects.",
    answer: true,
    explanation: "R distinguishes upper and lower case in names, so Data and data are separate.",
    source: "Lecture 1, naming" },
  { id: "tools-011", topic: "tools", type: "tf",
    prompt: "RStudio is the same program as R.",
    answer: false,
    explanation: "R is the language and engine; RStudio is a separate IDE that runs R. You can use R without RStudio.",
    source: "Lecture 1, R vs RStudio" },
  { id: "tools-012", topic: "tools", type: "tf",
    prompt: "R is free and open-source software.",
    answer: true,
    explanation: "R is open source and free to use, one reason for its wide adoption.",
    source: "Lecture 1, about R" },
  { id: "tools-013", topic: "tools", type: "single",
    prompt: "Which function combines several values into a single vector?",
    options: ["`c()`", "`vector()`", "`paste()`", "`combine()`"],
    answer: 0,
    explanation: "c() concatenates values into one vector, for example c(1, 2, 3).",
    source: "Lecture 1, vectors" },
  { id: "tools-014", topic: "tools", type: "single",
    prompt: "What does `setwd()` do?",
    options: ["Sets the working directory", "Shows the working directory", "Saves the workspace", "Sorts a vector"],
    answer: 0,
    explanation: "setwd() changes the working directory; getwd() shows it.",
    source: "Lecture 1, working directory" },
  { id: "tools-015", topic: "tools", type: "single",
    prompt: "How do you call the `filter` function from the dplyr package without attaching the whole package?",
    options: ["`dplyr::filter()`", "`dplyr$filter()`", "`filter.dplyr()`", "`library(dplyr)::filter()`"],
    answer: 0,
    explanation: "The package::function form calls a function directly from a package without library().",
    source: "Lecture 2, calling functions with `::`" },
  { id: "tools-016", topic: "tools", type: "tf",
    prompt: "The `::` operator lets you use a function from a package without attaching it with `library()`.",
    answer: true,
    explanation: "package::function reaches into an installed package for a single function.",
    source: "Lecture 2, calling functions with `::`" },
  { id: "tools-017", topic: "tools", type: "single",
    prompt: "Which function lists the objects currently in your environment?",
    options: ["`ls()`", "`rm()`", "`getwd()`", "`str()`"],
    answer: 0,
    explanation: "ls() lists the names of objects in memory. rm() removes them; str() shows structure.",
    source: "Lecture 2, environment" },
  { id: "tools-018", topic: "tools", type: "single",
    prompt: "Which call removes the object `x` from your environment?",
    options: ["`rm(x)`", "`delete(x)`", "`remove.object(x)`", "`x <- NULL` only"],
    answer: 0,
    explanation: "rm(x) deletes the object from the environment.",
    source: "Lecture 2, environment" },
  { id: "tools-019", topic: "tools", type: "single",
    prompt: "CRAN is:",
    options: [
      "The official repository of R packages",
      "An R code editor",
      "A data file format",
      "A plotting library"
    ],
    answer: 0,
    explanation: "CRAN (Comprehensive R Archive Network) hosts R itself and the official packages.",
    source: "Lecture 1, packages" },
  { id: "tools-020", topic: "tools", type: "multi",
    prompt: "Which of these validly assign the value 5 to `x`?",
    options: ["`x <- 5`", "`x = 5`", "`5 -> x`", "`x == 5`"],
    answer: [0, 1, 2],
    explanation: "<-, =, and the rightward -> all assign in R; == is a comparison, not an assignment. Note: the course teaches `<-` as the assignment operator, so `=` and `->` are valid R but outside course convention.",
    source: "Beyond course, general R assignment (course convention is `<-`, Lecture 2)" },
  { id: "tools-021", topic: "tools", type: "tf",
    prompt: "In RStudio, the Environment pane shows the objects currently loaded in memory.",
    answer: true,
    explanation: "The Environment pane lists your current variables and data objects.",
    source: "Lecture 1, RStudio panes" },
  { id: "tools-022", topic: "tools", type: "tf",
    prompt: "In RStudio you can run the current line of a script with a keyboard shortcut instead of retyping it in the console.",
    answer: true,
    explanation: "RStudio sends the current line or selection to the console with a run shortcut.",
    source: "Lecture 1, RStudio" },
  { id: "tools-023", topic: "tools", type: "single",
    prompt: "What is the working directory?",
    options: [
      "The folder R uses to resolve relative file paths",
      "The folder where R itself is installed",
      "The pane showing your variables",
      "The list of loaded packages"
    ],
    answer: 0,
    explanation: "Relative paths like data/x.csv are resolved from the working directory.",
    source: "Lecture 1, working directory" },
  { id: "tools-024", topic: "tools", type: "single",
    prompt: "Which symbol at the start of a console line means R is ready for a new command?",
    options: ["`>`", "`+`", "`#`", "`$`"],
    answer: 0,
    explanation: "The > prompt means R is idle and waiting. A + means a command is unfinished.",
    source: "Lecture 1, console" },
  { id: "tools-025", topic: "tools", type: "tf",
    prompt: "A `+` at the start of the console line means R is waiting for you to finish an incomplete command.",
    answer: true,
    explanation: "The continuation prompt + appears when a line is unfinished, for example an unclosed bracket.",
    source: "Lecture 1, console" },
  { id: "tools-026", topic: "tools", type: "single",
    prompt: "Which opens the help page for the function `sum`?",
    options: ["`?sum`", "`sum?`", "`str(sum)`", "`args(sum)`"],
    answer: 0,
    explanation: "A leading ? (or help(sum)) opens the documentation. args() and str() show other details.",
    source: "Lecture 1, help" },
  { id: "tools-027", topic: "tools", type: "single",
    prompt: "R scripts are conventionally saved with which file extension?",
    options: ["`.R`", "`.py`", "`.txt`", "`.docx`"],
    answer: 0,
    explanation: "Plain R scripts use the .R extension. (R Markdown uses .Rmd.)",
    source: "Lecture 1, scripts" },
  { id: "tools-028", topic: "tools", type: "tf",
    prompt: "A comment can appear at the end of a line, after some code, not only on its own line.",
    answer: true,
    explanation: "Anything after # on a line is a comment, whether the line starts with code or not.",
    source: "Lecture 1, comments" },
  { id: "tools-029", topic: "tools", type: "single",
    prompt: "Which function prints a value with quotes around strings and a leading index such as `[1]`?",
    options: ["`print()`", "`cat()`", "`message()`", "`writeLines()`"],
    answer: 0,
    explanation: "print() shows quotes and the [1] index. cat() prints plainly, without quotes or index.",
    source: "Lecture 1, output" },
  { id: "tools-030", topic: "tools", type: "single",
    prompt: "Top-level objects you create interactively are stored in the:",
    options: ["Global environment", "CRAN", "Console history", "Working directory"],
    answer: 0,
    explanation: "Objects you create at the top level live in the global environment (R_GlobalEnv), which the Environment pane displays. Objects created inside a function live in that function's own environment, not the global one.",
    source: "Lecture 2, environment" },

  // ---------------- PROGRAMMING BASICS ----------------
  { id: "prog-001", topic: "prog", type: "single",
    prompt: "What does this return?",
    code: "x <- c(1, 2, 3)\nx * 10",
    options: ["10 20 30", "60", "1 2 3 10", "Error"],
    answer: 0,
    explanation: "Arithmetic is vectorized: the scalar is applied element by element.",
    source: "Lecture 2, vectorization" },
  { id: "prog-002", topic: "prog", type: "tf",
    prompt: "`typeof(2L)` is \"integer\".",
    answer: true,
    explanation: "The L suffix forces an integer literal, so typeof() returns \"integer\".",
    source: "Lecture 2, types" },
  { id: "prog-003", topic: "prog", type: "multi",
    prompt: "Which statements about `&` versus `&&` are correct?",
    options: [
      "`&` is vectorized (element by element)",
      "`&&` evaluates only the first element",
      "`&&` is the form used inside if() conditions",
      "`&` returns a single value regardless of input length"
    ],
    answer: [0, 1, 2],
    explanation: "`&` works element-wise on whole vectors; `&&` looks at the first element only and is used for scalar if() logic.",
    source: "Lecture 2, logical operators" },
  { id: "prog-004", topic: "prog", type: "single",
    prompt: "What does `5 %% 3` return?",
    options: ["2", "1", "1.67", "15"],
    answer: 0,
    explanation: "%% is modulo (the remainder). 5 divided by 3 leaves remainder 2.",
    source: "Lecture 2, operators" },
  { id: "prog-005", topic: "prog", type: "single",
    prompt: "What does `5 %/% 3` return?",
    options: ["1", "2", "1.67", "0"],
    answer: 0,
    explanation: "%/% is integer division: the whole-number quotient, here 1.",
    source: "Lecture 2, operators" },
  { id: "prog-006", topic: "prog", type: "single",
    prompt: "What is the type of the result?",
    code: "c(TRUE, 2L, \"x\")",
    options: ["character", "logical", "integer", "list"],
    answer: 0,
    explanation: "Coercion promotes everything to the most flexible type present. Character wins, so all become strings.",
    source: "Lecture 2, coercion" },
  { id: "prog-007", topic: "prog", type: "single",
    prompt: "What is `total_sum` after this loop?",
    code: "numbers <- 1:4\ntotal_sum <- 0\nfor (i in 1:length(numbers)) {\n  if (i %% 2 == 0) total_sum <- total_sum + numbers[i]\n  else            total_sum <- total_sum + 2 * numbers[i]\n}",
    options: ["14", "10", "20", "8"],
    answer: 0,
    explanation: "i=1 odd:+2; i=2 even:+2; i=3 odd:+6; i=4 even:+4. Total = 14.",
    source: "Workshop 2, loop trace" },
  { id: "prog-008", topic: "prog", type: "tf",
    prompt: "`apply(m, MARGIN = 1, sum)` applies sum over the columns of matrix m.",
    answer: false,
    explanation: "MARGIN = 1 is rows, MARGIN = 2 is columns. This sums over rows.",
    source: "Lecture 2, apply" },
  { id: "prog-009", topic: "prog", type: "single",
    prompt: "Which call returns a double vector rather than a list?",
    options: ["purrr::map_dbl(1:3, f)", "lapply(1:3, f)", "purrr::map(1:3, f)", "list(1:3)"],
    answer: 0,
    explanation: "map() and lapply() return lists; map_dbl() returns a plain double vector.",
    source: "Lecture 2, functionals" },
  { id: "prog-010", topic: "prog", type: "single",
    prompt: "What does this return?",
    code: "seq(2, 10, by = 2)",
    options: ["2 4 6 8 10","2 10","2 4 6 8","1 2 3 ... 10"],
    answer: 0,
    explanation: "seq(from, to, by) builds a regular sequence: 2, 4, 6, 8, 10.",
    source: "Lecture 2, sequences" },
  { id: "prog-011", topic: "prog", type: "single",
    prompt: "What does this return?",
    code: "rev(c(1, 2, 3))",
    options: ["3 2 1","1 2 3","1 3","Error"],
    answer: 0,
    explanation: "rev() reverses the order of a vector.",
    source: "Lecture 2, vectors" },
  { id: "prog-012", topic: "prog", type: "single",
    prompt: "What does this return?",
    code: "length(c(4, 5, 6, 7))",
    options: ["4","7","22","3"],
    answer: 0,
    explanation: "length() gives the number of elements, here 4.",
    source: "Lecture 2, vectors" },
  { id: "prog-013", topic: "prog", type: "single",
    prompt: "What does this return?",
    code: "x <- c(10, 20, 30)\nx[2]",
    options: ["20","10","30","2"],
    answer: 0,
    explanation: "Indexing is 1-based, so x[2] is the second element, 20.",
    source: "Lecture 2, indexing" },
  { id: "prog-014", topic: "prog", type: "tf",
    prompt: "For a vector `x`, `x[-1]` returns `x` without its first element.",
    answer: true,
    explanation: "A negative index drops that position, so x[-1] removes the first element.",
    source: "Lecture 2, indexing" },
  { id: "prog-015", topic: "prog", type: "single",
    prompt: "What does this return?",
    code: "sum(1:5)",
    options: ["15","5","12","10"],
    answer: 0,
    explanation: "1:5 is 1 2 3 4 5, and their sum is 15.",
    source: "Lecture 2, functions" },
  { id: "prog-016", topic: "prog", type: "single",
    prompt: "What does this return?",
    code: "rep(0, 3)",
    options: ["0 0 0","0 3","3","0"],
    answer: 0,
    explanation: "rep(x, times) repeats x, giving 0 0 0.",
    source: "Lecture 2, vectors" },
  { id: "prog-017", topic: "prog", type: "single",
    prompt: "What does this return?",
    code: "c(1, 5, 3) > 2",
    options: ["FALSE TRUE TRUE","TRUE TRUE TRUE","TRUE FALSE FALSE","5 3"],
    answer: 0,
    explanation: "Comparison is vectorized element by element: 1>2 F, 5>2 T, 3>2 T.",
    source: "Lecture 2, comparison" },
  { id: "prog-018", topic: "prog", type: "single",
    prompt: "What does this return?",
    code: "2 %in% c(1, 2, 3)",
    options: ["TRUE","FALSE","2","NA"],
    answer: 0,
    explanation: "%in% tests membership: 2 is in the vector, so TRUE.",
    source: "Lecture 2, operators" },
  { id: "prog-019", topic: "prog", type: "tf",
    prompt: "`is.na(NA)` returns TRUE.",
    answer: true,
    explanation: "is.na() tests for missing values, and NA is missing, so TRUE.",
    source: "Lecture 2, missing values" },
  { id: "prog-020", topic: "prog", type: "single",
    prompt: "What does this return?",
    code: "sum(c(1, 2, NA, 4), na.rm = TRUE)",
    options: ["7","NA","3","Error"],
    answer: 0,
    explanation: "na.rm = TRUE ignores the NA, so 1 + 2 + 4 = 7.",
    source: "Lecture 2, missing values" },
  { id: "prog-021", topic: "prog", type: "single",
    prompt: "What does this return?",
    code: "paste0(\"a\", \"b\", \"c\")",
    options: ["\"abc\"","\"a b c\"","\"a, b, c\"","\"abc \""],
    answer: 0,
    explanation: "paste0() joins strings with no separator; paste() uses a space by default.",
    source: "Lecture 2, strings" },
  { id: "prog-022", topic: "prog", type: "single",
    prompt: "What does this return?",
    code: "nchar(\"hello\")",
    options: ["5","4","1","\"hello\""],
    answer: 0,
    explanation: "nchar() counts the characters in a string, here 5.",
    source: "Lecture 2, strings" },
  { id: "prog-023", topic: "prog", type: "multi",
    prompt: "Which of these are loop constructs in R?",
    options: ["`for`","`while`","`repeat`","`ifelse`"],
    answer: [0,1,2],
    explanation: "for, while, and repeat are loops. ifelse() is a vectorized conditional, not a loop.",
    source: "Lecture 2, loops" },
  { id: "prog-024", topic: "prog", type: "single",
    prompt: "What is `x` after this loop?",
    code: "x <- 0\nfor (i in 1:3) {\n  x <- x + i\n}",
    options: ["6","3","0","9"],
    answer: 0,
    explanation: "x accumulates 1 + 2 + 3 = 6.",
    source: "Lecture 2, loops" },
  { id: "prog-025", topic: "prog", type: "single",
    prompt: "What does this return?",
    code: "f <- function(a, b = 2) a + b\nf(5)",
    options: ["7","5","2","Error"],
    answer: 0,
    explanation: "b defaults to 2 when not supplied, so 5 + 2 = 7.",
    source: "Lecture 2, functions" },
  { id: "prog-026", topic: "prog", type: "single",
    prompt: "What does `seq_along(c(\"a\", \"b\", \"c\"))` return?",
    options: ["1 2 3","\"a\" \"b\" \"c\"","3","0 1 2"],
    answer: 0,
    explanation: "seq_along() returns index positions 1..length, here 1 2 3.",
    source: "Lecture 2, sequences" },
  { id: "prog-027", topic: "prog", type: "tf",
    prompt: "`sapply()` tries to simplify its result to a vector or matrix, while `lapply()` always returns a list.",
    answer: true,
    explanation: "That simplification is the main difference between sapply() and lapply().",
    source: "Lecture 2, functionals" },
  { id: "prog-028", topic: "prog", type: "single",
    prompt: "What does this return?",
    code: "x <- 4\nif (x > 3) \"big\" else \"small\"",
    options: ["\"big\"","\"small\"","TRUE","Error"],
    answer: 0,
    explanation: "4 > 3 is TRUE, so the if branch returns \"big\".",
    source: "Lecture 2, conditionals" },
  { id: "prog-029", topic: "prog", type: "single",
    prompt: "What does this return?",
    code: "abs(-7)",
    options: ["7","-7","0","Error"],
    answer: 0,
    explanation: "abs() gives the absolute value, here 7.",
    source: "Lecture 2, functions" },

  // ---------------- DATA STORAGE & ENCODING ----------------
  { id: "storage-001", topic: "storage", type: "single",
    prompt: "What is decimal 139 in binary?",
    options: ["10001011", "10000111", "11001010", "10101011"],
    answer: 0,
    explanation: "128 + 8 + 2 + 1 = 139, which is 10001011.",
    source: "Lecture 3, binary" },
  { id: "storage-002", topic: "storage", type: "single",
    prompt: "What is decimal 139 in hexadecimal?",
    options: ["8B", "B8", "FF", "8D"],
    answer: 0,
    explanation: "(8 x 16) + 11 = 139, and 11 is B, so 8B.",
    source: "Lecture 3, hexadecimal" },
  { id: "storage-003", topic: "storage", type: "tf",
    prompt: "Each hexadecimal digit corresponds to exactly 4 binary digits.",
    answer: true,
    explanation: "16 = 2^4, so one hex digit maps cleanly to a group of 4 bits.",
    source: "Lecture 3, hex/binary" },
  { id: "storage-004", topic: "storage", type: "single",
    prompt: "What does this return?",
    code: "0.3 - 0.2 == 0.1",
    options: ["FALSE", "TRUE", "NA", "Error"],
    answer: 0,
    explanation: "Floating-point imprecision makes the left side slightly off 0.1, so the comparison is FALSE.",
    source: "Lecture 3, floating point" },
  { id: "storage-005", topic: "storage", type: "single",
    prompt: "What is the correct way to compare two computed doubles for equality?",
    options: ["abs(a - b) < tolerance", "a == b", "identical(a, b)", "a = b"],
    answer: 0,
    explanation: "Because of floating-point error, compare within a small tolerance rather than with ==.",
    source: "Lecture 3, floating point" },
  { id: "storage-006", topic: "storage", type: "tf",
    prompt: "UTF-8 can represent characters beyond the original ASCII set.",
    answer: true,
    explanation: "UTF-8 is a Unicode encoding covering far more than ASCII, including accented and non-Latin characters.",
    source: "Lecture 3, encoding" },
  { id: "storage-007", topic: "storage", type: "single",
    prompt: "What is decimal 10 in binary?",
    options: ["1010","1000","1100","0110"],
    answer: 0,
    explanation: "8 + 2 = 10, which is 1010.",
    source: "Lecture 3, binary" },
  { id: "storage-008", topic: "storage", type: "single",
    prompt: "What is binary 1010 in decimal?",
    options: ["10","8","12","6"],
    answer: 0,
    explanation: "1010 is 8 + 0 + 2 + 0 = 10.",
    source: "Lecture 3, binary" },
  { id: "storage-009", topic: "storage", type: "single",
    prompt: "What is hexadecimal FF in decimal?",
    options: ["255","256","16","128"],
    answer: 0,
    explanation: "F is 15, so FF = (15 x 16) + 15 = 255.",
    source: "Lecture 3, hexadecimal" },
  { id: "storage-010", topic: "storage", type: "single",
    prompt: "How many bits are in one byte?",
    options: ["8","4","16","2"],
    answer: 0,
    explanation: "One byte is 8 bits.",
    source: "Lecture 3, bits and bytes" },
  { id: "storage-011", topic: "storage", type: "tf",
    prompt: "A single bit can hold only one of two values, 0 or 1.",
    answer: true,
    explanation: "A bit is binary: exactly two states, 0 or 1.",
    source: "Lecture 3, bits" },
  { id: "storage-012", topic: "storage", type: "single",
    prompt: "How many hexadecimal digits are needed to represent one byte?",
    options: ["2","1","4","8"],
    answer: 0,
    explanation: "Each hex digit covers 4 bits, so one byte (8 bits) needs 2 hex digits.",
    source: "Lecture 3, hex/binary" },
  { id: "storage-013", topic: "storage", type: "single",
    prompt: "What is decimal 5 in binary?",
    options: ["101","110","011","100"],
    answer: 0,
    explanation: "4 + 1 = 5, which is 101.",
    source: "Lecture 3, binary" },
  { id: "storage-014", topic: "storage", type: "single",
    prompt: "Why can `0.1 + 0.2 == 0.3` be FALSE in R?",
    options: ["Decimal fractions cannot always be stored exactly in binary floating point","R rounds all numbers to integers","== does not work on numbers","0.3 is not a valid number"],
    answer: 0,
    explanation: "Floating-point representation is not exact for these fractions, so a tiny error remains.",
    source: "Lecture 3, floating point" },
  { id: "storage-015", topic: "storage", type: "single",
    prompt: "What is the purpose of `iconv()` in R?",
    options: ["Convert text from one character encoding to another","Convert a number to a character","Read a CSV file","Compress a file"],
    answer: 0,
    explanation: "iconv() re-encodes text, for example from ISO-8859-1 to UTF-8.",
    source: "Lecture 3, encoding" },
  { id: "storage-016", topic: "storage", type: "tf",
    prompt: "A plain text file stores characters according to a character encoding.",
    answer: true,
    explanation: "Encodings like UTF-8 map the stored bytes to characters.",
    source: "Lecture 3, encoding" },
  { id: "storage-017", topic: "storage", type: "tf",
    prompt: "Hexadecimal is base 16 and uses the digits 0-9 and letters A-F.",
    answer: true,
    explanation: "Hex has 16 symbols: 0 through 9 then A through F for 10 to 15.",
    source: "Lecture 3, hexadecimal" },
  { id: "storage-018", topic: "storage", type: "single",
    prompt: "In R, which special value represents a missing value?",
    options: ["NA","NULL","NaN","Inf"],
    answer: 0,
    explanation: "NA marks a missing value. NaN is not-a-number, Inf is infinity, NULL is an empty object.",
    source: "Lecture 3, special values" },
  { id: "storage-019", topic: "storage", type: "single",
    prompt: "The binary system is base:",
    options: ["2","10","16","8"],
    answer: 0,
    explanation: "Binary is base 2.",
    source: "Lecture 3, number systems" },

  // ---------------- IMPORT & RECTANGULAR DATA ----------------
  { id: "import-001", topic: "import", type: "single",
    prompt: "Which function returns a tibble?",
    options: ["read_csv()", "read.csv()", "read.table()", "scan()"],
    answer: 0,
    explanation: "readr's read_csv() returns a tibble; base read.csv() returns a data.frame.",
    source: "Lecture 4, import" },
  { id: "import-002", topic: "import", type: "tf",
    prompt: "`read_csv()` from readr converts string columns to factors by default.",
    answer: false,
    explanation: "readr keeps strings as character. Old base read.csv() used to make factors; readr does not.",
    source: "Lecture 4, readr vs base" },
  { id: "import-003", topic: "import", type: "single",
    prompt: "What does this return?",
    code: "typeof(factor(c(\"a\", \"b\", \"a\")))",
    options: ["integer", "character", "factor", "double"],
    answer: 0,
    explanation: "A factor is stored as integers with a labels attribute, so typeof() is \"integer\" (class() is \"factor\").",
    source: "Lecture 4, factors" },
  { id: "import-004", topic: "import", type: "multi",
    prompt: "Which statements about tibbles versus data.frames are correct?",
    options: [
      "Tibbles print only the first rows plus column types",
      "Subsetting one tibble column keeps it a tibble",
      "data.frame historically converted strings to factors",
      "Tibbles do partial column-name matching"
    ],
    answer: [0, 1, 2],
    explanation: "Tibbles print compactly, keep tibble structure on subsetting, and do NOT do partial matching. Old data.frames auto-created factors.",
    source: "Lecture 4, tibble vs data.frame" },
  { id: "import-005", topic: "import", type: "single",
    prompt: "How many rows does the filtered result have?",
    code: "df <- data.frame(a = 1:3)\ndf[df$a > 1, ]",
    options: ["2", "1", "3", "0"],
    answer: 0,
    explanation: "Values greater than 1 are 2 and 3, so two rows are kept.",
    source: "Lecture 4, data frame subsetting" },
  { id: "import-006", topic: "import", type: "single",
    prompt: "What does `read_tsv(\"f.txt\", skip = 9)` do?",
    options: [
      "Skips the first 9 lines, then reads tab-separated data",
      "Reads only 9 lines",
      "Skips 9 columns",
      "Reads a comma-separated file"
    ],
    answer: 0,
    explanation: "skip = 9 ignores 9 leading lines (often metadata); read_tsv expects tab separators.",
    source: "Workshop 3, NASA temperature import" },
  { id: "import-007", topic: "import", type: "single",
    prompt: "Which function reads a semicolon-separated file (common in European CSVs)?",
    options: ["read_csv2()","read_csv()","read_tsv()","read.table2()"],
    answer: 0,
    explanation: "read_csv2() expects semicolons as separators and commas as decimal marks.",
    source: "Lecture 4, readr" },
  { id: "import-008", topic: "import", type: "single",
    prompt: "Which function lets you set any delimiter yourself?",
    options: ["read_delim(file, delim = \";\")","read_csv(file)","read_tsv(file)","scan(file)"],
    answer: 0,
    explanation: "read_delim() takes an explicit delim argument for any separator.",
    source: "Lecture 4, readr" },
  { id: "import-009", topic: "import", type: "single",
    prompt: "Which package reads Excel .xlsx files?",
    options: ["readxl","readr","haven","jsonlite"],
    answer: 0,
    explanation: "readxl::read_excel() reads .xls and .xlsx files.",
    source: "Lecture 4, importing Excel" },
  { id: "import-010", topic: "import", type: "single",
    prompt: "Which package reads Stata .dta and SPSS .sav files?",
    options: ["haven","readxl","rvest","readr"],
    answer: 0,
    explanation: "haven reads Stata (.dta), SPSS (.sav), and SAS files.",
    source: "Lecture 4, other formats" },
  { id: "import-011", topic: "import", type: "single",
    prompt: "What does `nrow(df)` return?",
    options: ["The number of rows","The number of columns","The column names","The first row"],
    answer: 0,
    explanation: "nrow() gives the row count; ncol() gives the column count.",
    source: "Lecture 4, data frames" },
  { id: "import-012", topic: "import", type: "single",
    prompt: "Which extracts the column `age` from a data frame `df`?",
    options: ["df$age","df@age","df->age","df::age"],
    answer: 0,
    explanation: "The $ operator selects a named column.",
    source: "Lecture 4, data frames" },
  { id: "import-013", topic: "import", type: "single",
    prompt: "What does `head(df, 3)` return?",
    options: ["The first 3 rows","The last 3 rows","3 random rows","Column 3"],
    answer: 0,
    explanation: "head(x, n) returns the first n rows; tail() returns the last.",
    source: "Lecture 4, inspecting data" },
  { id: "import-014", topic: "import", type: "single",
    prompt: "What does this return?",
    code: "df <- data.frame(a = c(5, 8, 8, 2))\nnrow(df)",
    options: ["4","2","1","8"],
    answer: 0,
    explanation: "The column has 4 values, so the data frame has 4 rows.",
    source: "Lecture 4, data frames" },
  { id: "import-015", topic: "import", type: "single",
    prompt: "Which function gives a compact overview of a data frame's structure and column types?",
    options: ["str()","sum()","plot()","paste()"],
    answer: 0,
    explanation: "str() shows the structure: types and first values of each column.",
    source: "Lecture 4, inspecting data" },
  { id: "import-016", topic: "import", type: "single",
    prompt: "How many rows does this keep?",
    code: "df <- data.frame(age = c(25, 40, 30, 18))\ndf[df$age >= 30, ]",
    options: ["2","3","1","4"],
    answer: 0,
    explanation: "Ages 40 and 30 satisfy >= 30, so two rows are kept.",
    source: "Lecture 4, subsetting" },
  { id: "import-017", topic: "import", type: "single",
    prompt: "What does `as.numeric(\"3.5\")` return?",
    options: ["3.5","\"3.5\"","3","NA"],
    answer: 0,
    explanation: "as.numeric() converts the string \"3.5\" to the number 3.5.",
    source: "Lecture 4, type conversion" },
  { id: "import-018", topic: "import", type: "tf",
    prompt: "Within a single data frame column, all values share the same type.",
    answer: true,
    explanation: "A column is a vector, and a vector is homogeneous in type.",
    source: "Lecture 4, data structures" },
  { id: "import-019", topic: "import", type: "multi",
    prompt: "Which of these are readr import functions?",
    options: ["read_csv()","read_tsv()","read_delim()","read.csv()"],
    answer: [0,1,2],
    explanation: "read_csv, read_tsv, read_delim are readr. read.csv (with a dot) is base R.",
    source: "Lecture 4, readr" },
  { id: "import-020", topic: "import", type: "single",
    prompt: "Which writes a data frame to a CSV file with readr?",
    options: ["write_csv(df, \"out.csv\")","read_csv(df)","save_csv(df)","to_csv(df)"],
    answer: 0,
    explanation: "readr::write_csv() writes a data frame to disk as CSV.",
    source: "Lecture 4, writing data" },
  { id: "import-021", topic: "import", type: "single",
    prompt: "What does `ncol(df)` return for `data.frame(a = 1:3, b = 4:6)`?",
    options: ["2","3","6","1"],
    answer: 0,
    explanation: "There are two columns, a and b, so ncol is 2.",
    source: "Lecture 4, data frames" },
  { id: "import-022", topic: "import", type: "single",
    prompt: "Which returns the column names of a data frame?",
    options: ["colnames(df)","rownames(df)","nrow(df)","values(df)"],
    answer: 0,
    explanation: "colnames() (or names()) returns the column names.",
    source: "Lecture 4, data frames" },
  { id: "import-023", topic: "import", type: "tf",
    prompt: "By default, the levels of a factor are ordered alphabetically.",
    answer: true,
    explanation: "Unless you specify levels, factor() orders them alphabetically.",
    source: "Lecture 4, factors" },

  // ---------------- NON-RECTANGULAR DATA ----------------
  { id: "nonrect-001", topic: "nonrect", type: "single",
    prompt: "Which package parses JSON into R lists?",
    options: ["jsonlite", "xml2", "rvest", "httr2"],
    answer: 0,
    explanation: "jsonlite::fromJSON() parses JSON. xml2 is for XML, rvest for HTML.",
    source: "Lecture 5, JSON" },
  { id: "nonrect-002", topic: "nonrect", type: "single",
    prompt: "Which call finds every <name> element at any depth in an XML document?",
    options: ["xml_find_all(doc, \".//name\")", "xml_child(doc, 1)", "xml_text(doc)", "read_xml(doc)"],
    answer: 0,
    explanation: "The XPath .//name matches <name> anywhere in the tree; xml_find_all returns all matches.",
    source: "Lecture 5, XML / XPath" },
  { id: "nonrect-003", topic: "nonrect", type: "tf",
    prompt: "In an XML tree of a <students> list, the individual student elements are siblings of one another.",
    answer: true,
    explanation: "Elements at the same level under one parent are siblings; each student is a child of <students>.",
    source: "Lecture 5, XML tree vocabulary" },
  { id: "nonrect-004", topic: "nonrect", type: "single",
    prompt: "Which function reads an HTML page so you can scrape it?",
    options: ["read_html()", "read_xml()", "fromJSON()", "read_csv()"],
    answer: 0,
    explanation: "rvest::read_html() loads a page; html_table() / html_elements() then extract content.",
    source: "Workshop 3, HTML web scraping" },
  { id: "nonrect-005", topic: "nonrect", type: "multi",
    prompt: "Which statements about JSON are correct?",
    options: [
      "Objects are key/value pairs written with { }",
      "Arrays are ordered lists written with [ ]",
      "Keys must be strings",
      "It requires closing tags like XML"
    ],
    answer: [0, 1, 2],
    explanation: "JSON uses { } objects and [ ] arrays with string keys, and unlike XML it has no closing tags.",
    source: "Lecture 5, JSON" },
  { id: "nonrect-006", topic: "nonrect", type: "tf",
    prompt: "A web page is considered semi-structured data because it can mix a clean table with free text.",
    answer: true,
    explanation: "HTML pages combine structured parts (tables) with unstructured parts (prose), hence semi-structured.",
    source: "Workshop 3, HTML web scraping" },
  { id: "nonrect-007", topic: "nonrect", type: "single",
    prompt: "In xml2, which returns all direct child nodes of a node?",
    options: ["xml_children()","xml_child()","xml_text()","xml_attr()"],
    answer: 0,
    explanation: "xml_children() returns all children; xml_child(node, n) returns one.",
    source: "Lecture 5, xml2" },
  { id: "nonrect-008", topic: "nonrect", type: "single",
    prompt: "Which extracts the text content from XML nodes?",
    options: ["xml_text()","xml_children()","xml_name()","read_xml()"],
    answer: 0,
    explanation: "xml_text() pulls out the text inside the selected nodes.",
    source: "Lecture 5, xml2" },
  { id: "nonrect-009", topic: "nonrect", type: "tf",
    prompt: "In JSON, keys are always written as strings.",
    answer: true,
    explanation: "JSON object keys must be strings in double quotes.",
    source: "Lecture 5, JSON" },
  { id: "nonrect-010", topic: "nonrect", type: "single",
    prompt: "Which rvest function extracts HTML tables into data frames?",
    options: ["html_table()","html_text()","read_xml()","fromJSON()"],
    answer: 0,
    explanation: "rvest::html_table() turns HTML tables into data frames.",
    source: "Workshop 3, HTML web scraping" },
  { id: "nonrect-011", topic: "nonrect", type: "tf",
    prompt: "An XML document has exactly one root element.",
    answer: true,
    explanation: "A well-formed XML document has a single root element containing all others.",
    source: "Lecture 5, XML structure" },
  { id: "nonrect-012", topic: "nonrect", type: "tf",
    prompt: "HTML is a markup language, not a programming language.",
    answer: true,
    explanation: "HTML marks up structure and content; it does not have programming logic.",
    source: "Workshop 3, HTML web scraping" },
  { id: "nonrect-013", topic: "nonrect", type: "single",
    prompt: "In XPath, what does the leading `//` mean, as in `//name`?",
    options: ["Match <name> at any depth in the document","Match only the root element","Comment out the query","Match the first <name> only"],
    answer: 0,
    explanation: "// selects matching nodes anywhere in the tree, regardless of depth.",
    source: "Lecture 5, XPath" },
  { id: "nonrect-014", topic: "nonrect", type: "multi",
    prompt: "Which of these are hierarchical (tree-structured) data formats?",
    options: ["XML","JSON","HTML","A flat CSV"],
    answer: [0,1,2],
    explanation: "XML, JSON, and HTML nest elements into trees. A flat CSV is rectangular, not hierarchical.",
    source: "Lecture 5, data formats" },
  { id: "nonrect-015", topic: "nonrect", type: "single",
    prompt: "Which reads an XML file into R?",
    options: ["read_xml()","read_html()","read_csv()","fromJSON()"],
    answer: 0,
    explanation: "xml2::read_xml() parses an XML document.",
    source: "Lecture 5, xml2" },
  { id: "nonrect-016", topic: "nonrect", type: "single",
    prompt: "In JSON, what encloses an ordered list of values?",
    options: ["Square brackets [ ]","Curly braces { }","Angle brackets < >","Parentheses ( )"],
    answer: 0,
    explanation: "Arrays use [ ]; objects (key/value pairs) use { }.",
    source: "Lecture 5, JSON" },
  { id: "nonrect-017", topic: "nonrect", type: "single",
    prompt: "A value can be stored in XML either as element text or as an:",
    options: ["Attribute","Index","Array","Pipe"],
    answer: 0,
    explanation: "XML values can be element-defined (text) or attribute-defined (name=\"value\").",
    source: "Lecture 5, XML" },
  { id: "nonrect-018", topic: "nonrect", type: "single",
    prompt: "Which returns the value of an XML attribute?",
    options: ["xml_attr()","xml_text()","xml_children()","xml_name()"],
    answer: 0,
    explanation: "xml_attr(node, \"attr\") reads a named attribute's value.",
    source: "Lecture 5, xml2" },
  { id: "nonrect-019", topic: "nonrect", type: "single", flagged: true,
    prompt: "In rvest, which selects page elements matching a CSS selector or XPath?",
    options: ["html_elements()","html_table()","read_html()","xml_text()"],
    answer: 0,
    explanation: "html_elements() (formerly html_nodes) selects nodes. Not confirmed in the extractable course text -- verify against the Workshop 3 slides/solution before relying on this one.",
    source: "Workshop 3, rvest (unconfirmed -- check slides)" },

  // ---------------- APIs ----------------
  { id: "apis-001", topic: "apis", type: "single",
    prompt: "In httr2, which function sends the request and returns a response?",
    options: ["req_perform(req)", "request(url)", "resp_body_json(resp)", "req_url_query(req)"],
    answer: 0,
    explanation: "request() builds it, req_perform() sends it, resp_body_json() parses the returned body.",
    source: "Guest lecture, httr2" },
  { id: "apis-002", topic: "apis", type: "single",
    prompt: "An HTTP status code of 200 means:",
    options: ["Success", "Not found", "Server error", "Redirect"],
    answer: 0,
    explanation: "200 signals a successful request. 404 is not found, 500 is server error.",
    source: "Guest lecture, HTTP" },
  { id: "apis-003", topic: "apis", type: "tf",
    prompt: "`resp_body_json()` parses a JSON response body into an R list.",
    answer: true,
    explanation: "It converts the JSON payload of the response into a nested R list.",
    source: "Guest lecture, httr2" },
  { id: "apis-004", topic: "apis", type: "multi",
    prompt: "Which are genuine advantages of using an API over manual download?",
    options: [
      "Automation of data retrieval",
      "Access to real-time data",
      "Fetch exactly the range or indicators you need",
      "Guaranteed absence of rate limits"
    ],
    answer: [0, 1, 2],
    explanation: "APIs automate and target retrieval, but they are commonly rate limited, so the last option is false.",
    source: "Guest lecture, APIs" },
  { id: "apis-005", topic: "apis", type: "single",
    prompt: "What does a rate limit on an API mean?",
    options: [
      "A cap on how many requests you may send per time window",
      "The speed of your internet connection",
      "The maximum size of a single response",
      "A fee charged per request"
    ],
    answer: 0,
    explanation: "Rate limiting restricts the number of calls allowed in a given period.",
    source: "Guest lecture, APIs" },
  { id: "apis-006", topic: "apis", type: "tf",
    prompt: "Many APIs require an API key or token to authenticate the caller.",
    answer: true,
    explanation: "Keys/tokens identify and authorise the caller, and are often needed before data is returned.",
    source: "Guest lecture, authentication" },
  { id: "apis-007", topic: "apis", type: "single",
    prompt: "Which HTTP method is normally used to retrieve data from an API?",
    options: ["GET","POST","DELETE","PUT"],
    answer: 0,
    explanation: "GET requests retrieve data; POST sends data, PUT updates, DELETE removes.",
    source: "Guest lecture, HTTP methods" },
  { id: "apis-008", topic: "apis", type: "single",
    prompt: "An HTTP status code of 404 means:",
    options: ["Not found","Success","Server error","Unauthorized"],
    answer: 0,
    explanation: "404 means the requested resource was not found.",
    source: "Guest lecture, HTTP status" },
  { id: "apis-009", topic: "apis", type: "single",
    prompt: "In httr2, which builds a request object from a URL?",
    options: ["request()","req_perform()","resp_body_json()","resp_status()"],
    answer: 0,
    explanation: "request(url) creates the request; req_perform() then sends it.",
    source: "Guest lecture, httr2" },
  { id: "apis-010", topic: "apis", type: "single",
    prompt: "In httr2, which adds query parameters to a request URL?",
    options: ["req_url_query()","req_perform()","resp_status()","request()"],
    answer: 0,
    explanation: "req_url_query() appends ?name=value parameters to the request.",
    source: "Guest lecture, httr2" },
  { id: "apis-011", topic: "apis", type: "tf",
    prompt: "JSON is a common format for the data an API returns.",
    answer: true,
    explanation: "Most modern REST APIs return JSON (sometimes XML).",
    source: "Guest lecture, APIs" },
  { id: "apis-012", topic: "apis", type: "single",
    prompt: "In httr2, which returns the HTTP status code of a response?",
    options: ["resp_status()","resp_body_json()","req_perform()","request()"],
    answer: 0,
    explanation: "resp_status(resp) gives the numeric status code, such as 200.",
    source: "Guest lecture, httr2" },
  { id: "apis-013", topic: "apis", type: "single",
    prompt: "An HTTP status code in the 500 range indicates:",
    options: ["A server-side error","Success","A missing page","A redirect"],
    answer: 0,
    explanation: "5xx codes indicate the server failed to fulfil a valid request.",
    source: "Guest lecture, HTTP status" },
  { id: "apis-014", topic: "apis", type: "tf",
    prompt: "An API key should be kept private rather than shared publicly.",
    answer: true,
    explanation: "Keys authenticate you; exposing one lets others use your access.",
    source: "Guest lecture, authentication" },
  { id: "apis-015", topic: "apis", type: "single",
    prompt: "REST APIs are typically accessed over which protocol?",
    options: ["HTTP","FTP","SMTP","SSH"],
    answer: 0,
    explanation: "REST APIs are accessed via HTTP or HTTPS requests.",
    source: "Guest lecture, REST" },
  { id: "apis-016", topic: "apis", type: "tf",
    prompt: "The general httr2 flow is: build the request, perform it, then check the status and parse the body.",
    answer: true,
    explanation: "request() then req_perform() then resp_status() and resp_body_json() is the standard flow.",
    source: "Guest lecture, httr2" },

  // ---------------- DATA PREPARATION ----------------
  { id: "prep-001", topic: "prep", type: "single",
    prompt: "Which function reshapes data from wide to long?",
    options: ["pivot_longer()", "pivot_wider()", "bind_rows()", "left_join()"],
    answer: 0,
    explanation: "pivot_longer() stacks columns into long format; pivot_wider() does the reverse.",
    source: "Lecture 7, reshaping" },
  { id: "prep-002", topic: "prep", type: "single",
    prompt: "How many rows does the inner join return?",
    code: "temperature$scale   # c(\"Cel\", \"Cel\", \"F\")\nconversions$scale   # c(\"Celsius\", \"Fahrenheit\")\ninner_join(temperature, conversions, by = \"scale\")",
    options: ["0", "3", "2", "5"],
    answer: 0,
    explanation: "The keys never match (\"Cel\" vs \"Celsius\", \"F\" vs \"Fahrenheit\"), so an inner join keeps no rows.",
    source: "Lecture 8, joins" },
  { id: "prep-003", topic: "prep", type: "tf",
    prompt: "`left_join()` keeps all rows from the left table, filling unmatched right-hand columns with NA.",
    answer: true,
    explanation: "A left join preserves every master (left) row; missing matches on the right become NA.",
    source: "Lecture 8, joins" },
  { id: "prep-004", topic: "prep", type: "multi",
    prompt: "Which of these are dplyr verbs?",
    options: ["select()", "filter()", "mutate()", "merge()"],
    answer: [0, 1, 2],
    explanation: "select, filter, mutate are dplyr. merge() is base R (the dplyr equivalent is the join family).",
    source: "Lecture 8, dplyr" },
  { id: "prep-005", topic: "prep", type: "single",
    prompt: "Which stacks rows and fills missing columns with NA instead of erroring?",
    options: ["bind_rows()", "rbind()", "cbind()", "c()"],
    answer: 0,
    explanation: "dplyr::bind_rows() is flexible about differing columns; base rbind() errors if they do not match.",
    source: "Lecture 8, binding" },
  { id: "prep-006", topic: "prep", type: "single",
    prompt: "What is `case_when()` used for?",
    options: [
      "Assigning values based on several conditions in order",
      "Only a single true/false condition",
      "Joining two tables",
      "Drawing a plot"
    ],
    answer: 0,
    explanation: "case_when() is the dplyr multi-condition if/else-if chain; ifelse() handles a single condition.",
    source: "Lecture 8, case_when" },
  { id: "prep-007", topic: "prep", type: "single",
    prompt: "Which dplyr verb keeps only rows meeting a condition?",
    options: ["filter()","select()","arrange()","mutate()"],
    answer: 0,
    explanation: "filter() keeps rows; select() keeps columns.",
    source: "Lecture 8, dplyr" },
  { id: "prep-008", topic: "prep", type: "single",
    prompt: "Which dplyr verb keeps or drops columns?",
    options: ["select()","filter()","arrange()","summarise()"],
    answer: 0,
    explanation: "select() chooses columns by name.",
    source: "Lecture 8, dplyr" },
  { id: "prep-009", topic: "prep", type: "single",
    prompt: "Which dplyr verb creates or changes a column?",
    options: ["mutate()","filter()","arrange()","select()"],
    answer: 0,
    explanation: "mutate() adds new columns or modifies existing ones.",
    source: "Lecture 8, dplyr" },
  { id: "prep-010", topic: "prep", type: "single",
    prompt: "Which sorts rows in descending order of `x`?",
    options: ["arrange(desc(x))","arrange(x)","sort(x)","order(x)"],
    answer: 0,
    explanation: "arrange(desc(x)) sorts descending; arrange(x) sorts ascending.",
    source: "Lecture 8, dplyr" },
  { id: "prep-011", topic: "prep", type: "single",
    prompt: "Which pair collapses groups into per-group summary statistics?",
    options: ["group_by() then summarise()","select() then filter()","mutate() then arrange()","bind_rows() then join()"],
    answer: 0,
    explanation: "group_by() defines groups; summarise() computes one row of statistics per group.",
    source: "Lecture 8, dplyr" },
  { id: "prep-012", topic: "prep", type: "single",
    prompt: "What does the pipe `|>` do?",
    options: ["Passes the left-hand result as the first argument of the next function","Adds two vectors","Comments out a line","Compares two values"],
    answer: 0,
    explanation: "The pipe feeds the left result into the next function, enabling readable chains.",
    source: "Lecture 7, the pipe" },
  { id: "prep-013", topic: "prep", type: "single",
    prompt: "Which join keeps all rows from the left table and matching rows from the right?",
    options: ["left_join()","inner_join()","right_join()","semi_join()"],
    answer: 0,
    explanation: "left_join() preserves every left row, filling unmatched right columns with NA.",
    source: "Lecture 8, joins" },
  { id: "prep-014", topic: "prep", type: "single",
    prompt: "Which join keeps only rows with a match in BOTH tables?",
    options: ["inner_join()","left_join()","full_join()","anti_join()"],
    answer: 0,
    explanation: "inner_join() keeps only matching rows.",
    source: "Lecture 8, joins" },
  { id: "prep-015", topic: "prep", type: "single",
    prompt: "Which join keeps all rows from both tables?",
    options: ["full_join()","inner_join()","left_join()","semi_join()"],
    answer: 0,
    explanation: "full_join() keeps every row from both, with NA where there is no match.",
    source: "Lecture 8, joins" },
  { id: "prep-016", topic: "prep", type: "single",
    prompt: "Which reshapes data from long to wide?",
    options: ["pivot_wider()","pivot_longer()","bind_rows()","separate()"],
    answer: 0,
    explanation: "pivot_wider() spreads to wide; pivot_longer() stacks to long.",
    source: "Lecture 7, reshaping" },
  { id: "prep-017", topic: "prep", type: "single",
    prompt: "What does this return?",
    code: "df <- data.frame(x = c(1, 2, 2, 3, 3, 3))\nnrow(distinct(df))",
    options: ["3","6","2","1"],
    answer: 0,
    explanation: "distinct() removes duplicate rows, leaving the unique values 1, 2, 3.",
    source: "Lecture 8, distinct" },
  { id: "prep-018", topic: "prep", type: "tf",
    prompt: "Tidy data means each variable is a column, each observation is a row, and each value is one cell.",
    answer: true,
    explanation: "That is the definition of tidy data.",
    source: "Lecture 7, tidy data" },
  { id: "prep-019", topic: "prep", type: "single",
    prompt: "Which stacks two data frames on top of each other by rows?",
    options: ["bind_rows()","left_join()","pivot_wider()","select()"],
    answer: 0,
    explanation: "bind_rows() appends rows; joins combine by key, not by stacking.",
    source: "Lecture 8, binding" },
  { id: "prep-020", topic: "prep", type: "single",
    prompt: "For long-format analysis and plotting, which layout is usually preferred?",
    options: ["Long","Wide","Neither, format never matters","Matrix only"],
    answer: 0,
    explanation: "Long format suits group_by/summarise and ggplot2; wide suits presentation.",
    source: "Lecture 7, reshaping" },
  { id: "prep-021", topic: "prep", type: "single",
    prompt: "What does this pipeline produce conceptually?",
    code: "df |>\n  filter(score > 50) |>\n  summarise(avg = mean(score))",
    options: ["The mean score among rows where score exceeds 50","All rows with score over 50","The number of rows","An error"],
    answer: 0,
    explanation: "It filters to score > 50, then summarises the mean of those scores.",
    source: "Lecture 8, dplyr pipeline" },
  { id: "prep-022", topic: "prep", type: "single",
    prompt: "Which handles several conditions in order, like a multi-branch if/else?",
    options: ["case_when()","ifelse()","filter()","mutate()"],
    answer: 0,
    explanation: "case_when() evaluates conditions in sequence; ifelse() handles a single condition.",
    source: "Lecture 8, case_when" },
  { id: "prep-023", topic: "prep", type: "single",
    prompt: "Which tidyr function splits one column into several based on a separator?",
    options: ["separate()","unite()","pivot_longer()","distinct()"],
    answer: 0,
    explanation: "separate() splits a column; unite() is the reverse.",
    source: "Lecture 7/8, tidyr" },

  // ---------------- EDA & VISUALISATION ----------------
  { id: "viz-001", topic: "viz", type: "single",
    prompt: "In ggplot2, a colour that should vary with a variable must be placed:",
    options: ["Inside aes()", "Outside aes()", "In theme()", "In facet_wrap()"],
    answer: 0,
    explanation: "Mapping to data goes inside aes(); a fixed constant colour goes outside aes().",
    source: "Lecture 9, aesthetics" },
  { id: "viz-002", topic: "viz", type: "tf",
    prompt: "`geom_bar()` by default plots the y-value you supply in the data.",
    answer: false,
    explanation: "geom_bar() counts rows by default. Use geom_bar(stat = \"identity\") to plot supplied y-values.",
    source: "Lecture 10, geoms" },
  { id: "viz-003", topic: "viz", type: "single",
    prompt: "Which layer adds a linear trend line?",
    options: ["geom_smooth(method = \"lm\")", "geom_point()", "geom_line()", "geom_col()"],
    answer: 0,
    explanation: "geom_smooth(method = \"lm\") fits and draws a linear model line.",
    source: "Lecture 10, stats layers" },
  { id: "viz-004", topic: "viz", type: "multi",
    prompt: "Which are among Tufte's visualisation principles?",
    options: [
      "Minimise the lie factor",
      "Maximise the data-ink ratio",
      "Maximise data density",
      "Always add 3-D effects"
    ],
    answer: [0, 1, 2],
    explanation: "Tufte argues for honesty (lie factor near 1), high data-ink ratio, and dense data. 3-D effects distort.",
    source: "Lecture 10, Tufte" },
  { id: "viz-005", topic: "viz", type: "single",
    prompt: "What does `mean(x, na.rm = TRUE)` do?",
    options: [
      "Ignores NA values when computing the mean",
      "Deletes rows containing NA",
      "Returns NA if any value is missing",
      "Replaces NA with 0"
    ],
    answer: 0,
    explanation: "na.rm = TRUE tells the function to skip NA values in the calculation.",
    source: "Lecture 9, missing values" },
  { id: "viz-006", topic: "viz", type: "tf",
    prompt: "`facet_wrap(~var)` creates one panel per level of var.",
    answer: true,
    explanation: "Faceting splits the plot into small multiples, one panel for each value of the faceting variable.",
    source: "Lecture 9, facets" },
  { id: "viz-007", topic: "viz", type: "single",
    prompt: "Which geom draws a scatter plot of individual points?",
    options: ["geom_point()","geom_line()","geom_bar()","geom_boxplot()"],
    answer: 0,
    explanation: "geom_point() plots one point per observation.",
    source: "Lecture 9, geoms" },
  { id: "viz-008", topic: "viz", type: "single",
    prompt: "In ggplot2, what does `aes()` do?",
    options: ["Maps variables to visual properties like x, y, and colour","Sets the plot title","Chooses the file format","Removes missing values"],
    answer: 0,
    explanation: "aes() defines the mapping from data columns to aesthetics.",
    source: "Lecture 9, aesthetics" },
  { id: "viz-009", topic: "viz", type: "single",
    prompt: "Which geom shows the distribution of a single continuous variable?",
    options: ["geom_histogram()","geom_point()","geom_line()","geom_col()"],
    answer: 0,
    explanation: "geom_histogram() bins one continuous variable to show its distribution.",
    source: "Lecture 10, geoms" },
  { id: "viz-010", topic: "viz", type: "single", flagged: true,
    prompt: "Which geom draws a box-and-whisker plot?",
    options: ["geom_boxplot()","geom_area()","geom_point()","geom_tile()"],
    answer: 0,
    explanation: "geom_boxplot() summarises a distribution with quartiles and outliers. Not confirmed in the extractable course text -- verify against the Lecture 10 slides before relying on this one.",
    source: "Lecture 10, geoms (unconfirmed -- check slides)" },
  { id: "viz-011", topic: "viz", type: "tf",
    prompt: "`geom_col()` plots the y-values you supply, rather than counting rows.",
    answer: true,
    explanation: "geom_col() uses supplied y-values, equivalent to geom_bar(stat = \"identity\").",
    source: "Lecture 10, geoms" },
  { id: "viz-012", topic: "viz", type: "single",
    prompt: "Which layers are combined in ggplot2 with the `+` operator?",
    options: ["Data and aesthetics, geoms, and themes","Only two data frames","Rows of a table","Package names"],
    answer: 0,
    explanation: "ggplot2 builds a plot by adding layers (aes, geoms, facets, themes) with +.",
    source: "Lecture 9, grammar of graphics" },
  { id: "viz-013", topic: "viz", type: "single",
    prompt: "Which function sets axis titles and the plot title?",
    options: ["labs()","aes()","facet_wrap()","geom_point()"],
    answer: 0,
    explanation: "labs(title =, x =, y =) sets labels.",
    source: "Lecture 9, labels" },
  { id: "viz-014", topic: "viz", type: "single",
    prompt: "To make every point a single fixed blue, where does `color = \"blue\"` go?",
    options: ["Outside aes(), in the geom","Inside aes()","In facet_wrap()","In labs()"],
    answer: 0,
    explanation: "A constant aesthetic is set outside aes(): geom_point(color = \"blue\").",
    source: "Lecture 9, aesthetics" },
  { id: "viz-015", topic: "viz", type: "single",
    prompt: "Which base R function gives a quick numeric overview (min, median, mean, max) of each column?",
    options: ["summary()","plot()","mean()","nrow()"],
    answer: 0,
    explanation: "summary() reports per-column summary statistics.",
    source: "Lecture 9, EDA" },
  { id: "viz-016", topic: "viz", type: "single",
    prompt: "Which counts how many times each category occurs in a vector?",
    options: ["table()","sum()","mean()","arrange()"],
    answer: 0,
    explanation: "table() produces a frequency count of categories.",
    source: "Lecture 9, EDA" },
  { id: "viz-017", topic: "viz", type: "single",
    prompt: "Which drops rows containing any NA?",
    options: ["na.omit()","is.na()","mean()","sum()"],
    answer: 0,
    explanation: "na.omit() removes rows with missing values.",
    source: "Lecture 9, missing values" },
  { id: "viz-018", topic: "viz", type: "tf",
    prompt: "Tufte's guidance discourages 3-D effects and pie charts because they can distort comparison.",
    answer: true,
    explanation: "Such decoration reduces clarity and can mislead; Tufte favours clean, honest displays.",
    source: "Lecture 10, Tufte" },
  { id: "viz-019", topic: "viz", type: "single",
    prompt: "For showing a trend of one continuous variable over time, which geom is most natural?",
    options: ["geom_line()","geom_bar()","geom_boxplot()","geom_tile()"],
    answer: 0,
    explanation: "geom_line() connects points in order, suiting time trends.",
    source: "Lecture 10, choosing a geom" },
  { id: "viz-020", topic: "viz", type: "single",
    prompt: "Which returns a logical vector marking which elements are missing?",
    options: ["is.na(x)","na.omit(x)","complete.cases(x)","mean(x)"],
    answer: 0,
    explanation: "is.na(x) is TRUE at positions that are NA.",
    source: "Lecture 9, missing values" },
  { id: "viz-021", topic: "viz", type: "single",
    prompt: "Which returns a logical vector marking rows that have NO missing values?",
    options: ["complete.cases(df)","is.na(df)","na.rm(df)","drop_na(df)"],
    answer: 0,
    explanation: "complete.cases() is TRUE for rows without any NA.",
    source: "Lecture 9, missing values" },
];

if (typeof module !== "undefined") module.exports = { TOPICS, QUESTIONS };
