/*
 * QUESTION BANK  -  Data Handling in R (course 3,230,1.00)
 * ---------------------------------------------------------
 * Each question is one object. Schema:
 *
 *   id          unique string, "<topicKey>-NNN"          (e.g. "prog-007")
 *   topic       one of the TOPIC keys defined in TOPICS below
 *   type        "tf" | "single" | "multi"
 *   prompt      the question text. Wrap inline code in backticks `like this`
 *   code        OPTIONAL multi-line code block shown in a monospace box
 *   options     array of strings. OMIT for "tf" (True/False is implied)
 *   answer      tf -> true/false | single -> option index | multi -> array of indices
 *   explanation short correction shown after answering
 *   source      where it comes from, for your own verification (hidden from stats)
 *   flagged     OPTIONAL true if the author was unsure  ->  verify this one first
 *
 * To add questions with Claude Code, just append objects to QUESTIONS.
 * Keep ids unique. Nothing else needs to change; the app reads TOPICS + QUESTIONS.
 */

const TOPICS = [
  { key: "tools",   name: "Tools & Setup",            blurb: "R, RStudio, paths, help" },
  { key: "prog",    name: "Programming Basics",       blurb: "vectors, operators, loops, functions" },
  { key: "storage", name: "Data Storage & Encoding",  blurb: "binary, hex, floats, encoding" },
  { key: "import",  name: "Import & Rectangular Data", blurb: "readr, types, data frames, factors" },
  { key: "nonrect", name: "Non-Rectangular Data",      blurb: "XML, JSON, HTML, scraping" },
  { key: "apis",    name: "APIs",                      blurb: "httr2, requests, responses" },
  { key: "prep",    name: "Data Preparation",          blurb: "tidy, reshape, joins, dplyr" },
  { key: "viz",     name: "EDA & Visualisation",       blurb: "EDA, missing values, ggplot2" },
];

const QUESTIONS = [
  // ---------------- TOOLS & SETUP ----------------
  { id: "tools-001", topic: "tools", type: "tf",
    prompt: "In R, both `<-` and `=` can assign a value, but `<-` is the community convention.",
    answer: true,
    explanation: "Both work for assignment. `<-` is the preferred, conventional operator in R style guides.",
    source: "Lecture 1, assignment" },
  { id: "tools-002", topic: "tools", type: "single",
    prompt: "Which function returns your current working directory?",
    options: ["getwd()", "setwd()", "cwd()", "dir()"],
    answer: 0,
    explanation: "getwd() prints the working directory. setwd() changes it; dir() lists files.",
    source: "Lecture 1, working directory" },
  { id: "tools-003", topic: "tools", type: "single",
    prompt: "You want to run an entire saved script from the console. Which call does that?",
    code: "# script lives at code/clean.R",
    options: ["source(\"code/clean.R\")", "run(\"code/clean.R\")", "import(\"code/clean.R\")", "exec(\"code/clean.R\")"],
    answer: 0,
    explanation: "source() executes a whole R script file from disk in the current session.",
    source: "Lecture 1, source()" },
  { id: "tools-004", topic: "tools", type: "tf",
    prompt: "R vectors are indexed starting at 0.",
    answer: false,
    explanation: "R is 1-based. The first element is x[1], not x[0]. (This differs from Python.)",
    source: "Lecture 2, indexing" },
  { id: "tools-005", topic: "tools", type: "single",
    prompt: "What does `?sum` do?",
    options: ["Opens the help page for sum()", "Computes a running sum", "Checks if sum exists", "Prints the source code of sum()"],
    answer: 0,
    explanation: "A leading ? opens the documentation for a function.",
    source: "Lecture 1, help" },
  { id: "tools-006", topic: "tools", type: "single",
    prompt: "In a file path, what does `..` refer to?",
    options: ["The parent directory", "The current directory", "The home directory", "The root directory"],
    answer: 0,
    explanation: ".. is the parent folder; . is the current folder; ~ is home.",
    source: "Lecture 1, paths" },

  // ---------------- PROGRAMMING BASICS ----------------
  { id: "prog-001", topic: "prog", type: "single",
    prompt: "What does this return?",
    code: "x <- c(1, 2, 3)\nx * 10",
    options: ["10 20 30", "60", "1 2 3 10", "Error"],
    answer: 0,
    explanation: "Arithmetic is vectorized: the scalar is applied element by element.",
    source: "Lecture 2, vectorization" },
  { id: "prog-002", topic: "prog", type: "tf",
    prompt: "`typeof(2L)` is \"integer\".",
    answer: true,
    explanation: "The L suffix forces an integer literal, so typeof() returns \"integer\".",
    source: "Lecture 2, types" },
  { id: "prog-003", topic: "prog", type: "multi",
    prompt: "Which statements about `&` versus `&&` are correct?",
    options: [
      "`&` is vectorized (element by element)",
      "`&&` evaluates only the first element",
      "`&&` is the form used inside if() conditions",
      "`&` returns a single value regardless of input length"
    ],
    answer: [0, 1, 2],
    explanation: "`&` works element-wise on whole vectors; `&&` looks at the first element only and is used for scalar if() logic.",
    source: "Lecture 2, logical operators" },
  { id: "prog-004", topic: "prog", type: "single",
    prompt: "What does `5 %% 3` return?",
    options: ["2", "1", "1.67", "15"],
    answer: 0,
    explanation: "%% is modulo (the remainder). 5 divided by 3 leaves remainder 2.",
    source: "Lecture 2, operators" },
  { id: "prog-005", topic: "prog", type: "single",
    prompt: "What does `5 %/% 3` return?",
    options: ["1", "2", "1.67", "0"],
    answer: 0,
    explanation: "%/% is integer division: the whole-number quotient, here 1.",
    source: "Lecture 2, operators" },
  { id: "prog-006", topic: "prog", type: "single",
    prompt: "What is the type of the result?",
    code: "c(TRUE, 2L, \"x\")",
    options: ["character", "logical", "integer", "list"],
    answer: 0,
    explanation: "Coercion promotes everything to the most flexible type present. Character wins, so all become strings.",
    source: "Lecture 2, coercion" },
  { id: "prog-007", topic: "prog", type: "single",
    prompt: "What is `total_sum` after this loop?",
    code: "numbers <- 1:4\ntotal_sum <- 0\nfor (i in 1:length(numbers)) {\n  if (i %% 2 == 0) total_sum <- total_sum + numbers[i]\n  else            total_sum <- total_sum + 2 * numbers[i]\n}",
    options: ["14", "10", "20", "8"],
    answer: 0,
    explanation: "i=1 odd:+2; i=2 even:+2; i=3 odd:+6; i=4 even:+4. Total = 14.",
    source: "Workshop 2, loop trace" },
  { id: "prog-008", topic: "prog", type: "tf",
    prompt: "`apply(m, MARGIN = 1, sum)` applies sum over the columns of matrix m.",
    answer: false,
    explanation: "MARGIN = 1 is rows, MARGIN = 2 is columns. This sums over rows.",
    source: "Lecture 2, apply" },
  { id: "prog-009", topic: "prog", type: "single",
    prompt: "Which call returns a double vector rather than a list?",
    options: ["purrr::map_dbl(1:3, f)", "lapply(1:3, f)", "purrr::map(1:3, f)", "list(1:3)"],
    answer: 0,
    explanation: "map() and lapply() return lists; map_dbl() returns a plain double vector.",
    source: "Lecture 2, functionals" },

  // ---------------- DATA STORAGE & ENCODING ----------------
  { id: "storage-001", topic: "storage", type: "single",
    prompt: "What is decimal 139 in binary?",
    options: ["10001011", "10000111", "11001010", "10101011"],
    answer: 0,
    explanation: "128 + 8 + 2 + 1 = 139, which is 10001011.",
    source: "Lecture 3, binary" },
  { id: "storage-002", topic: "storage", type: "single",
    prompt: "What is decimal 139 in hexadecimal?",
    options: ["8B", "B8", "FF", "8D"],
    answer: 0,
    explanation: "(8 x 16) + 11 = 139, and 11 is B, so 8B.",
    source: "Lecture 3, hexadecimal" },
  { id: "storage-003", topic: "storage", type: "tf",
    prompt: "Each hexadecimal digit corresponds to exactly 4 binary digits.",
    answer: true,
    explanation: "16 = 2^4, so one hex digit maps cleanly to a group of 4 bits.",
    source: "Lecture 3, hex/binary" },
  { id: "storage-004", topic: "storage", type: "single",
    prompt: "What does this return?",
    code: "0.3 - 0.2 == 0.1",
    options: ["FALSE", "TRUE", "NA", "Error"],
    answer: 0,
    explanation: "Floating-point imprecision makes the left side slightly off 0.1, so the comparison is FALSE.",
    source: "Lecture 3, floating point" },
  { id: "storage-005", topic: "storage", type: "single",
    prompt: "What is the correct way to compare two computed doubles for equality?",
    options: ["abs(a - b) < tolerance", "a == b", "identical(a, b)", "a = b"],
    answer: 0,
    explanation: "Because of floating-point error, compare within a small tolerance rather than with ==.",
    source: "Lecture 3, floating point" },
  { id: "storage-006", topic: "storage", type: "tf",
    prompt: "UTF-8 can represent characters beyond the original ASCII set.",
    answer: true,
    explanation: "UTF-8 is a Unicode encoding covering far more than ASCII, including accented and non-Latin characters.",
    source: "Lecture 3, encoding" },

  // ---------------- IMPORT & RECTANGULAR DATA ----------------
  { id: "import-001", topic: "import", type: "single",
    prompt: "Which function returns a tibble?",
    options: ["read_csv()", "read.csv()", "read.table()", "scan()"],
    answer: 0,
    explanation: "readr's read_csv() returns a tibble; base read.csv() returns a data.frame.",
    source: "Lecture 4, import" },
  { id: "import-002", topic: "import", type: "tf",
    prompt: "`read_csv()` from readr converts string columns to factors by default.",
    answer: false,
    explanation: "readr keeps strings as character. Old base read.csv() used to make factors; readr does not.",
    source: "Lecture 4, readr vs base" },
  { id: "import-003", topic: "import", type: "single",
    prompt: "What does this return?",
    code: "typeof(factor(c(\"a\", \"b\", \"a\")))",
    options: ["integer", "character", "factor", "double"],
    answer: 0,
    explanation: "A factor is stored as integers with a labels attribute, so typeof() is \"integer\" (class() is \"factor\").",
    source: "Lecture 4, factors" },
  { id: "import-004", topic: "import", type: "multi",
    prompt: "Which statements about tibbles versus data.frames are correct?",
    options: [
      "Tibbles print only the first rows plus column types",
      "Subsetting one tibble column keeps it a tibble",
      "data.frame historically converted strings to factors",
      "Tibbles do partial column-name matching"
    ],
    answer: [0, 1, 2],
    explanation: "Tibbles print compactly, keep tibble structure on subsetting, and do NOT do partial matching. Old data.frames auto-created factors.",
    source: "Lecture 4, tibble vs data.frame" },
  { id: "import-005", topic: "import", type: "single",
    prompt: "How many rows does the filtered result have?",
    code: "df <- data.frame(a = 1:3)\ndf[df$a > 1, ]",
    options: ["2", "1", "3", "0"],
    answer: 0,
    explanation: "Values greater than 1 are 2 and 3, so two rows are kept.",
    source: "Lecture 4, data frame subsetting" },
  { id: "import-006", topic: "import", type: "single",
    prompt: "What does `read_tsv(\"f.txt\", skip = 9)` do?",
    options: [
      "Skips the first 9 lines, then reads tab-separated data",
      "Reads only 9 lines",
      "Skips 9 columns",
      "Reads a comma-separated file"
    ],
    answer: 0,
    explanation: "skip = 9 ignores 9 leading lines (often metadata); read_tsv expects tab separators.",
    source: "Workshop 3, NASA temperature import" },

  // ---------------- NON-RECTANGULAR DATA ----------------
  { id: "nonrect-001", topic: "nonrect", type: "single",
    prompt: "Which package parses JSON into R lists?",
    options: ["jsonlite", "xml2", "rvest", "httr2"],
    answer: 0,
    explanation: "jsonlite::fromJSON() parses JSON. xml2 is for XML, rvest for HTML.",
    source: "Lecture 5, JSON" },
  { id: "nonrect-002", topic: "nonrect", type: "single",
    prompt: "Which call finds every <name> element at any depth in an XML document?",
    options: ["xml_find_all(doc, \".//name\")", "xml_child(doc, 1)", "xml_text(doc)", "read_xml(doc)"],
    answer: 0,
    explanation: "The XPath .//name matches <name> anywhere in the tree; xml_find_all returns all matches.",
    source: "Lecture 5, XML / XPath" },
  { id: "nonrect-003", topic: "nonrect", type: "tf",
    prompt: "In an XML tree of a <students> list, the individual student elements are siblings of one another.",
    answer: true,
    explanation: "Elements at the same level under one parent are siblings; each student is a child of <students>.",
    source: "Lecture 5, XML tree vocabulary" },
  { id: "nonrect-004", topic: "nonrect", type: "single",
    prompt: "Which function reads an HTML page so you can scrape it?",
    options: ["read_html()", "read_xml()", "fromJSON()", "read_csv()"],
    answer: 0,
    explanation: "rvest::read_html() loads a page; html_table() / html_elements() then extract content.",
    source: "Lecture 5, rvest" },
  { id: "nonrect-005", topic: "nonrect", type: "multi",
    prompt: "Which statements about JSON are correct?",
    options: [
      "Objects are key/value pairs written with { }",
      "Arrays are ordered lists written with [ ]",
      "Keys must be strings",
      "It requires closing tags like XML"
    ],
    answer: [0, 1, 2],
    explanation: "JSON uses { } objects and [ ] arrays with string keys, and unlike XML it has no closing tags.",
    source: "Lecture 5, JSON" },
  { id: "nonrect-006", topic: "nonrect", type: "tf",
    prompt: "A web page is considered semi-structured data because it can mix a clean table with free text.",
    answer: true,
    explanation: "HTML pages combine structured parts (tables) with unstructured parts (prose), hence semi-structured.",
    source: "Lecture 5, HTML" },

  // ---------------- APIs ----------------
  { id: "apis-001", topic: "apis", type: "single",
    prompt: "In httr2, which function sends the request and returns a response?",
    options: ["req_perform(req)", "request(url)", "resp_body_json(resp)", "req_url_query(req)"],
    answer: 0,
    explanation: "request() builds it, req_perform() sends it, resp_body_json() parses the returned body.",
    source: "Guest lecture, httr2" },
  { id: "apis-002", topic: "apis", type: "single",
    prompt: "An HTTP status code of 200 means:",
    options: ["Success", "Not found", "Server error", "Redirect"],
    answer: 0,
    explanation: "200 signals a successful request. 404 is not found, 500 is server error.",
    source: "Guest lecture, HTTP" },
  { id: "apis-003", topic: "apis", type: "tf",
    prompt: "`resp_body_json()` parses a JSON response body into an R list.",
    answer: true,
    explanation: "It converts the JSON payload of the response into a nested R list.",
    source: "Guest lecture, httr2" },
  { id: "apis-004", topic: "apis", type: "multi",
    prompt: "Which are genuine advantages of using an API over manual download?",
    options: [
      "Automation of data retrieval",
      "Access to real-time data",
      "Fetch exactly the range or indicators you need",
      "Guaranteed absence of rate limits"
    ],
    answer: [0, 1, 2],
    explanation: "APIs automate and target retrieval, but they are commonly rate limited, so the last option is false.",
    source: "Guest lecture, APIs" },
  { id: "apis-005", topic: "apis", type: "single",
    prompt: "What does a rate limit on an API mean?",
    options: [
      "A cap on how many requests you may send per time window",
      "The speed of your internet connection",
      "The maximum size of a single response",
      "A fee charged per request"
    ],
    answer: 0,
    explanation: "Rate limiting restricts the number of calls allowed in a given period.",
    source: "Guest lecture, APIs" },
  { id: "apis-006", topic: "apis", type: "tf",
    prompt: "Many APIs require an API key or token to authenticate the caller.",
    answer: true,
    explanation: "Keys/tokens identify and authorise the caller, and are often needed before data is returned.",
    source: "Guest lecture, authentication" },

  // ---------------- DATA PREPARATION ----------------
  { id: "prep-001", topic: "prep", type: "single",
    prompt: "Which function reshapes data from wide to long?",
    options: ["pivot_longer()", "pivot_wider()", "bind_rows()", "left_join()"],
    answer: 0,
    explanation: "pivot_longer() stacks columns into long format; pivot_wider() does the reverse.",
    source: "Lecture 7, reshaping" },
  { id: "prep-002", topic: "prep", type: "single",
    prompt: "How many rows does the inner join return?",
    code: "temperature$scale   # c(\"Cel\", \"Cel\", \"F\")\nconversions$scale   # c(\"Celsius\", \"Fahrenheit\")\ninner_join(temperature, conversions, by = \"scale\")",
    options: ["0", "3", "2", "5"],
    answer: 0,
    explanation: "The keys never match (\"Cel\" vs \"Celsius\", \"F\" vs \"Fahrenheit\"), so an inner join keeps no rows.",
    source: "Lecture 7, joins" },
  { id: "prep-003", topic: "prep", type: "tf",
    prompt: "`left_join()` keeps all rows from the left table, filling unmatched right-hand columns with NA.",
    answer: true,
    explanation: "A left join preserves every master (left) row; missing matches on the right become NA.",
    source: "Lecture 7, joins" },
  { id: "prep-004", topic: "prep", type: "multi",
    prompt: "Which of these are dplyr verbs?",
    options: ["select()", "filter()", "mutate()", "merge()"],
    answer: [0, 1, 2],
    explanation: "select, filter, mutate are dplyr. merge() is base R (the dplyr equivalent is the join family).",
    source: "Lecture 7, dplyr" },
  { id: "prep-005", topic: "prep", type: "single",
    prompt: "Which stacks rows and fills missing columns with NA instead of erroring?",
    options: ["bind_rows()", "rbind()", "cbind()", "c()"],
    answer: 0,
    explanation: "dplyr::bind_rows() is flexible about differing columns; base rbind() errors if they do not match.",
    source: "Lecture 7, binding" },
  { id: "prep-006", topic: "prep", type: "single",
    prompt: "What is `case_when()` used for?",
    options: [
      "Assigning values based on several conditions in order",
      "Only a single true/false condition",
      "Joining two tables",
      "Drawing a plot"
    ],
    answer: 0,
    explanation: "case_when() is the dplyr multi-condition if/else-if chain; ifelse() handles a single condition.",
    source: "Lecture 7, case_when" },

  // ---------------- EDA & VISUALISATION ----------------
  { id: "viz-001", topic: "viz", type: "single",
    prompt: "In ggplot2, a colour that should vary with a variable must be placed:",
    options: ["Inside aes()", "Outside aes()", "In theme()", "In facet_wrap()"],
    answer: 0,
    explanation: "Mapping to data goes inside aes(); a fixed constant colour goes outside aes().",
    source: "Lecture 10, aesthetics" },
  { id: "viz-002", topic: "viz", type: "tf",
    prompt: "`geom_bar()` by default plots the y-value you supply in the data.",
    answer: false,
    explanation: "geom_bar() counts rows by default. Use geom_bar(stat = \"identity\") (or geom_col()) to plot supplied y-values.",
    source: "Lecture 10, geoms" },
  { id: "viz-003", topic: "viz", type: "single",
    prompt: "Which layer adds a linear trend line?",
    options: ["geom_smooth(method = \"lm\")", "geom_point()", "geom_line()", "geom_col()"],
    answer: 0,
    explanation: "geom_smooth(method = \"lm\") fits and draws a linear model line.",
    source: "Lecture 10, stats layers" },
  { id: "viz-004", topic: "viz", type: "multi",
    prompt: "Which are among Tufte's visualisation principles?",
    options: [
      "Minimise the lie factor",
      "Maximise the data-ink ratio",
      "Maximise data density",
      "Always add 3-D effects"
    ],
    answer: [0, 1, 2],
    explanation: "Tufte argues for honesty (lie factor near 1), high data-ink ratio, and dense data. 3-D effects distort.",
    source: "Lecture 10, Tufte" },
  { id: "viz-005", topic: "viz", type: "single",
    prompt: "What does `mean(x, na.rm = TRUE)` do?",
    options: [
      "Ignores NA values when computing the mean",
      "Deletes rows containing NA",
      "Returns NA if any value is missing",
      "Replaces NA with 0"
    ],
    answer: 0,
    explanation: "na.rm = TRUE tells the function to skip NA values in the calculation.",
    source: "Lecture 9, missing values" },
  { id: "viz-006", topic: "viz", type: "tf",
    prompt: "`facet_wrap(~var)` creates one panel per level of var.",
    answer: true,
    explanation: "Faceting splits the plot into small multiples, one panel for each value of the faceting variable.",
    source: "Lecture 10, facets" },
];

if (typeof module !== "undefined") module.exports = { TOPICS, QUESTIONS };
